image: fedora/latest
packages:
  - golang-bin
sources:
  - https://git.sr.ht/~fnux/yggdrasil-toy-nodes
environment:
  GOPATH: /tmp/go
  GOBIN: /tmp/go/bin
tasks:
  - build: |
      cd yggdrasil-toy-nodes
      make getDeps
      make client
      make server
