image: fedora/31
packages:
  - golang-bin
sources:
  - https://git.sr.ht/~fnux/yggdrasil-http-proxy
environment:
  GOPATH: /tmp/go
  GOBIN: /tmp/go/bin
tasks:
  - build: |
      cd yggdrasil-http-proxy
      make getDeps
      make build
